//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using VendorManagementSystem.Interfaces;

    public partial class CompanyProject : ISoftDeletable
    {
        public string guid { get; set; }
        public string company_guid { get; set; }
        public string project_guid { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Project Project { get; set; }
    }
}
